version: '3.3'

services:
  postgres:
    image: callmenaul/alzheimer-postgres:v2.0
    container_name: alzheimer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alzheimer_diagnosing
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - alzheimer-network
    restart: unless-stopped
    ports:
      - "5432:5432"

  backend:
    image: callmenaul/alzheimer-backend:v2.0
    container_name: alzheimer-backend
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alzheimer_diagnosing
      PERFORM_MIGRATION: "true"
    networks:
      - alzheimer-network
    depends_on:
      - postgres
    command: [ "node", "server.js" ]
    restart: unless-stopped

  app:
    image: callmenaul/alzheimer-app:v2.0
    container_name: alzheimer-app
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alzheimer_diagnosing
    depends_on:
      - backend
      - postgres
    networks:
      - alzheimer-network
    volumes:
      - mri-uploads:/app/uploads
    restart: unless-stopped
    ports:
      - "80:80"

  diagnosing-server:
    image: callmenaul/alzheimer-diagnosing-server:v16.0
    container_name: alzheimer-diagnosing-server
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - mri-uploads:/app/uploads
    networks:
      - alzheimer-network
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - app

# Mạng
networks:
  alzheimer-network:
    driver: bridge

# Volumes
volumes:
  postgres-data:
    driver: local
  mri-uploads:
    driver: local
