version: '3.3'

services:
  postgres:
    image: callmenaul/alzheimer-postgres:v1.0
    container_name: alzheimer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alzheimer_diagnosing
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - alzheimer-network
    restart: unless-stopped
    ports:
      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  backend:
    image: callmenaul/alzheimer-backend:v1.0
    container_name: alzheimer-backend
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alzheimer_diagnosing
      PERFORM_MIGRATION: "true"
    networks:
      - alzheimer-network
    depends_on:
      - postgres
    command: [ "node", "server.js" ]
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 1G
#        reservations:
#          cpus: '0.25'
#          memory: 512M

  app:
    image: callmenaul/alzheimer-app:v1.0
    container_name: alzheimer-app
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alzheimer_diagnosing
    depends_on:
      - backend
      - postgres
    networks:
      - alzheimer-network
    volumes:
      - mri-uploads:/app/uploads
    restart: unless-stopped
    ports:
      - "80:80"
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 1G
#        reservations:
#          cpus: '0.25'
#          memory: 512M

  diagnosing-server:
    image: callmenaul/alzheimer-diagnosing-server:v2.0
    container_name: alzheimer-diagnosing-server
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - mri-uploads:/app/uploads
    networks:
      - alzheimer-network
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - app
#    deploy:
#      resources:
#        limits:
#          cpus: '2.0'
#          memory: 4G
#        reservations:
#          cpus: '0.5'
#          memory: 2G
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3

# Mạng
networks:
  alzheimer-network:
    driver: bridge

# Volumes
volumes:
  postgres-data:
    driver: local
  mri-uploads:
    driver: local
